### ISSUE TITLE
Fails to download: LinkNotFoundError

### ISSUE THREAD

**Issue by zenny** [raspberrypilearning/fl-data-downloader#14]
Hi,

Tried to run this without success with or without '-d' option:

```
$ fl-data-dl umich instructional-methods-in-health-professions-education -d team_members
using cache   - /home/zenny/.fl-data-dl-cache
Enter your FutureLearn username and password
Username : 
Password :
Filename: ./2020-10-24-08-24-00_team_members.csv
downloading   - umich_runs
Traceback (most recent call last):
  File "/home/zenny/.local/bin/fl-data-dl", line 8, in <module>
    sys.exit(fl_data_dl())
  File "/home/zenny/.local/lib/python3.9/site-packages/fl_data_downloader/__init__.py", line 42, in fl_data_dl
    download_data(organisation=args.organisation, courses=args.course, datasets=args.dataset, directory=output_dir, use_cache=not args.no_cache)
  File "/home/zenny/.local/lib/python3.9/site-packages/fl_data_downloader/data.py", line 532, in download_data
    dataset_df = fl.get_dataset_for_course(course, dataset)
  File "/home/zenny/.local/lib/python3.9/site-packages/fl_data_downloader/data.py", line 200, in get_dataset_for_course
    runs_df = self.runs
  File "/home/zenny/.local/lib/python3.9/site-packages/fl_data_downloader/data.py", line 439, in runs
    self._runs = self.get_runs()
  File "/home/zenny/.local/lib/python3.9/site-packages/fl_data_downloader/data.py", line 295, in get_runs
    form = self._browser.select_form('form[class="m-table-filter__checkboxes"]')
  File "/home/zenny/.local/lib/python3.9/site-packages/mechanicalsoup/stateful_browser.py", line 207, in select_form
    raise LinkNotFoundError()
mechanicalsoup.utils.LinkNotFoundError
```

The related course is : https://www.futurelearn.com/courses/instructional-methods-in-health-professions-education/1/ run by University of Michingan, fyi.

Any clue?

Cheers, and stay safe,
/z

**Comment by martinohanlon** [comment]
Hi, sorry I didnt have notifications on for this repo and missed the issue.

I cant test for your course as I dont have access to your courses.

I have however tested for one of our courses and I didnt experience an issue.

Have you done an upgrade of the tool recently? There was an issue back in August when FL changed their website which caused the tool to break. 

You can upgrade using:

```
pip3 install fl-data-downloader --upgrade
```

Let me know how you get on.

**Comment by martinohanlon** [comment]
Closing as no response.
